### ISSUE TITLE
Partition writer is probably introducing new lines

### ISSUE THREAD

**Issue by anilshanbhag** [mitdbg/mdindex#20]
Observed that in the partitions written out, very rarely there are two newlines between records.
This creates an error as we get a super tiny record.

**Comment by luyi0619** [comment]
we should remove line 59 from https://github.com/mitdbg/mdindex/blob/master/src/main/java/core/upfront/build/PartitionWriter.java

It writes out a int, not a byte of '\n'

+1 at line 199 and line 203 in https://github.com/mitdbg/mdindex/blob/master/src/main/java/core/upfront/build/InputReader.java

After that, we can solve this issue!

**Comment by anilshanbhag** [comment]
Agreed. Good catch at that int vs byte. 
Could you fix and above and commit it ? 
Also remove the the case at line 100 in PartitionIterator.

**Comment by luyi0619** [comment]
Done!
