### ISSUE TITLE
A bug in Query constructor

### ISSUE THREAD

**Issue by luyi0619** [mitdbg/mdindex#26]
```java
public Query(String predString) {
		String[] parts = predString.split(";");
		this.predicates = new Predicate[parts.length - 1];
		for (int i = 0; i < parts.length - 1; i++) {
			this.predicates[i] = new Predicate(parts[i]);
		}
	}
```

should be 

```java
public Query(String predString) {
		String[] parts = predString.split(";");
		this.predicates = new Predicate[parts.length];
		for (int i = 0; i < parts.length; i++) {
			this.predicates[i] = new Predicate(parts[i]);
		}
	}
```

**Comment by luyi0619** [comment]
@anilshanbhag Can you confirm this? Thanks

**Comment by anilshanbhag** [comment]
I think this is done because the format is a;b; so the last part is empty

**Comment by luyi0619** [comment]
@anilshanbhag can you take a look at Query.toString(). I don't think there is a ; at last

**Comment by anilshanbhag** [comment]
This seems like a serious bug. It doesn't affect the current query but it does affect the query window which is read from the queries file. So the cost estimates were potentially all wrong.
