### ISSUE TITLE
Server bug in InputReader.java

### ISSUE THREAD

**Issue by luyi0619** [mitdbg/mdindex#32]
line 187, 199.

If we put \n in RawIndexKey and the last attribute of a record is a string, we cannot go to the right bucket based on RobustTree. 

The result is we have non-empty bucket in the index, but empty data blocks.

**Comment by anilshanbhag** [comment]
The fix may not be the right one. 
Right now we are breaking records by \n. If the last field is a string and has \n, we are in trouble.

Your fix will include the \n as a part of the key. This will give error when the last attribute is int as it will try to parse 3\n as int. 

Maybe the right way to do it is to encode \n's present in the attribute values.

**Comment by luyi0619** [comment]
There is no \n in the record now, there was.

**Comment by anilshanbhag** [comment]
Cool, got it now. Closing this.
